import { API_BASE_URL } from "./config";

/**
 * Subscribes a user to the newsletter.
 *
 * Sends subscriber details, such as email and optional user information,
 * to the newsletter subscription endpoint.
 *
 * @param {Object} subscriberData - Newsletter subscriber details.
 * @returns {Promise<Object>} API response after successful subscription.
 * @throws {Error} Throws an error if the subscription request fails.
 */
export const subscribeNewsletter = async (subscriberData) => {
  try {
    const response = await fetch(`${API_BASE_URL}/newsletter/subscribe`, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify(subscriberData),
    });

    const data = await response.json();

    if (!response.ok) {
      throw new Error(data.message || "Failed to subscribe");
    }

    return data;
  } catch (error) {
    console.error("API Error (subscribeNewsletter):", error);
    throw error;
  }
};

/**
 * Unsubscribes a user from the newsletter using an unsubscribe token.
 *
 * The token is usually generated by the backend and sent to the subscriber,
 * for example through an unsubscribe link in an email.
 *
 * @param {string} token - Unique unsubscribe token for the subscriber.
 * @returns {Promise<Object>} API response after successful unsubscription.
 * @throws {Error} Throws an error if the unsubscribe request fails.
 */
export const unsubscribeNewsletter = async (token) => {
  try {
    const response = await fetch(
      `${API_BASE_URL}/newsletter/unsubscribe/${token}`,
    );

    const data = await response.json();

    if (!response.ok) {
      throw new Error(data.message || "Failed to unsubscribe");
    }

    return data;
  } catch (error) {
    console.error("API Error (unsubscribeNewsletter):", error);
    throw error;
  }
};
